repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        pass_filenames: true
        exclude: baselayer|node_modules|doc|data
  - repo: local
    hooks:
      - id: ESLint
        name: ESLint
        entry: npx eslint -c .eslintrc.yaml --fix
        language: system
        files: \.[j][t]sx?$
        types: [file]
