name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jest:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Run jest
        uses: npx jest
