name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Install problematic library
        run: npm install react-native-reanimated
      - name: Run jest
        run: npx jest
