name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package.json') }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install system dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

          sudo apt install -y wget nodejs

          pip install pre-commit

          export NPM_PACKAGES="${HOME}/.npm-packages"
          export PATH=${NPM_PACKAGES}/bin:$PATH
          export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

          sudo npm -g install npm@latest

          which python; python --version
          echo npm $(npm --version)
          echo node $(node --version)

      - name: Formatting and linting checks
        if: github.ref != 'refs/heads/main'
        run: |
          pip install pre-commit
          pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}

      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: log

      - name: Upload test post-mortem reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results
          path: test-results
