name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Run build
        run: npx expo export -p ios

  android-build:
    name: Android Dev Build
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Run build
        run: npx expo export -p android

  web-build:
    name: Android Dev Build
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Run build
        run: npx expo export -p web
