name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install pod dependency
        run: |
          bundle exec pod install
      - name: Build iOS JS Bundle
        run: |
          yarn run package-ios
      - name: Install bundler
        run: |
          gem install bundler
      - name: Install gem plugins
        run: |
          bundle install
      - name: Run fastlane
        run: |
          bundle exec fastlane build_testflight
  android-build:
    name: Android Dev Build
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo from main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: yarn install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          yarn run package-android
      - name: Delete Android build duplicate assets resource
        run: yarn run delete-pics
      - name: Install bundler
        run: |
          gem install bundler
      - name: Install gem plugins
        run: |
          bundle install
      - name: Run fastlane
        run: |
          bundle exec fastlane build_qa
